name: zero-bs-haskell
version: 0.1.0.0
github: "dougflip/zero-bs-haskell"
license: BSD3
author: "Doug DiFilippo"
maintainer: "douglasdifilippo@gmail.com"
copyright: "2019 Doug DiFilippo"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dougflip/zero-bs-haskell#readme>

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass

dependencies:
  - aeson
  - base
  - containers
  - zero-bullshit

library:
  source-dirs: src

executables:
  zero-bs-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zero-bs-haskell

tests:
  zero-bs-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zero-bs-haskell
      - tasty
      - tasty-hunit
